"""added user_config

Revision ID: 20977d90a4db
Revises: f58fbacae09b
Create Date: 2025-03-28 03:23:37.458247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20977d90a4db'
down_revision = 'f58fbacae09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_name', sa.String(length=100), nullable=True),
    sa.Column('max_size', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_config')
    # ### end Alembic commands ###
