"""added col in requests

Revision ID: 6b8cb3b92cfc
Revises: f574371a4371
Create Date: 2025-04-09 12:26:41.528526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8cb3b92cfc'
down_revision = 'f574371a4371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_users')
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_unit', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('superuser_id', sa.Integer(), nullable=False))

    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.alter_column('max_size',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.alter_column('max_size',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_column('superuser_id')
        batch_op.drop_column('req_unit')

    op.create_table('t_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('isActive', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('superuser_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey_1')
    )
    # ### end Alembic commands ###
