"""edited requests

Revision ID: ecceffb01d57
Revises: 6b8cb3b92cfc
Create Date: 2025-04-09 12:35:02.081981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecceffb01d57'
down_revision = '6b8cb3b92cfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.alter_column('req_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_column('req_unit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('req_unit', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.alter_column('req_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
