"""updated config

Revision ID: fab3ccbd593c
Revises: 9c390b130e8d
Create Date: 2025-04-03 08:52:29.295764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab3ccbd593c'
down_revision = '9c390b130e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_upgraded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.drop_column('storage_upgraded')

    # ### end Alembic commands ###
